### ISSUE TITLE
Query support for IDs of type ulong

### ISSUE THREAD

**Issue by Floowey** [mbdavid/LiteDB.Studio#34]
When trying to query a database entry with an ID of datatype ulong, an exception that the Parse to int32 has failed.
I'm using a POCO class to store UserAccounts for Discord Users (hence why the id is a ulong), the BSON (correctly) looks like this

```/* 1 */
{
  "_id": {"$numberLong": "300339714311847936"},
  "name": "Floowey"
}
```

However when I try to query for this with

```
SELECT $ FROM UserAccount WHERE _id=300339714311847936;
```

I get the following Exception:
```
Value was either too large or too small for an Int32.

===================================================
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at LiteDB.BsonExpressionParser.TryParseInt(Tokenizer tokenizer, BsonDocument parameters)
   at LiteDB.BsonExpressionParser.ParseSingleExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpressionParser.ParseFullExpression(Tokenizer tokenizer, ExpressionContext context, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpression.ParseAndCompile(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpression.Create(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters)
   at LiteDB.SqlParser.ParseSelect()
   at LiteDB.SqlParser.Execute()
   at LiteDB.LiteDatabase.Execute(TextReader commandReader, BsonDocument parameters)
   at LiteDB.Studio.MainForm.CreateThread(TaskData task) in C:\(Redacted)\LiteDB.Studio\LiteDB.Studio\Forms\MainForm.cs:line 324
```

I see that the issue is that it never intends to expect a different number format other than `int`; Is this something that could possibly be adapted?

**Comment by lbnascimento** [comment]
@Floowey A few things:

1. This issue should actually be in the LiteDB repository, so I'll close it (after this answer) and, if you have further questions, you can create a new issue in the LiteDB repo.

2. The query `select $ from UserAccount where _id={"$numberLong": "300339714311847936"}` should work fine for you.

3. Even though the parser currently expects a long to be represented with the `$numberLong` subdocument, it should be relatively simple to make it work without it, so I'll consider making this change in the following days.

4. LiteDB does not support `UInt64`, only `Int64`, so it is strognly recommended that you change the Id field in your class to `Int64`. There is a know issue that, in methods that take a single `BsonValue` (like `LiteCollection<T>.FindById(BsonValue)`), C# opts to implicitly convert the `UInt64` to `Double` (instead of `Int64`), and `Double` is known to have precision loss at such magnitudes. If you actually need to go over `Int64.MaxValue`, you should just use `string`.
